name: Build and Upload libraries

on: push

jobs:
 build-libs:
   name: Build Libraries And Upload Release
   runs-on: ubuntu-latest
   steps:
    - name: Clone
      id: checkout
      uses: actions/checkout@v3
      with:
        ref: concedo
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git curl bzip2 -y
    - name: Compiling libraries
      id: make_build
      run: |
        chmod +x koboldcpp_make_libs_only.sh
        ./koboldcpp_make_libs_only.sh
    - name: Packaging Libraries 
      run: |
        tar -czvf KoboldCPP_libraries.tar.gz *.so
        zip KoboldCPP_libraries.zip *.so
    - name: Make And Upload Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        name: Release ${{vars.VERSION}}
        tag_name: ${{vars.VERSION}}-${{github.run_id}}
        files: |
          ./KoboldCPP_libraries*